# Generated by Django 5.2.7 on 2025-10-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='kiteconnect_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kiteconnect_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kiteconnect_secret_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
