# Generated by Django 5.2.7 on 2025-11-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_kiteconnect_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us more about yourself', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trade_threshold',
            field=models.FloatField(blank=True, help_text='Maximum value per trade', null=True),
        ),
    ]
