# Generated by Django 5.2.7 on 2025-11-28 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stockdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=15)),
                ('diversification_score', models.FloatField(default=0.0, help_text='Score 0-100 based on sector spread')),
                ('win_rate', models.FloatField(default=0.0, help_text='Percentage of profitable trades')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
