# Generated by Django 5.2.7 on 2025-11-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_leaderboardsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +919876543210)', max_length=20, null=True),
        ),
    ]
